### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by natebb** [niklas-heer/pocketcasts-stats#107]
After following the instructions I get the following error in my GitLab build. I'm assuming I'm missing something in AirTable, but I can't figure it out. I copied the base and deleted all the records. However, if I add a new record the autonumber starts with the last number. I'm not sure if it's using that as an index.

84 Traceback (most recent call last):
85   File "./app.py", line 134, in <module>
86     previous_record[0]["fields"] != record
87 IndexError: list index out of range
91 ERROR: Job failed: exit code 1

**Comment by niklas-heer** [comment]
@natebb thank you for your contribution. I fixed how first records are being written to Airtable. Now it should work. 

Could you please verify it?

**Comment by natebb** [comment]
Sorry for the late notice as I've had a busy week, but yes the pipeline has been passing now since you pushed the fix. Thanks!

**Comment by niklas-heer** [comment]
@natebb you are welcome 🙂
