### ISSUE TITLE
Special characters in password

### ISSUE THREAD

**Issue by michaelcgorman** [niklas-heer/pocketcasts-stats#108]
The README currently says:

> IMPORTANT: You cannot use the `$` symbol in the environment variables!

While true, this extends beyond the `$` symbol. I originally had other special characters in my PocketCasts password and the build failed. When I changed my password to remove special characters, the build succeeded. I would suggest amending the documentation to include other special characters.

**Comment by niklas-heer** [comment]
Hey @michaelcgorman thank you for mentioning it. I will include it in the `README.md`.

Also a happy new year to you and have fun using the tool! 🎉

**Comment by michaelcgorman** [comment]
Cheers! Thanks for all of your work on this tool.

**Comment by niklas-heer** [comment]
You're welcome 😊
